[package]
name = "malti_split"
version = "0.1.0"
edition = "2024"

[dependencies]
hound = "3.5.1"
rustfft = "6.2.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
symphonia = "0.5.4"
